# Generated by Django 4.1.7 on 2023-11-21 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_application_telegram_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='telegram_user_id',
        ),
    ]
